language: python
python:
  - "3.6"

install:
  - pip install pytest
  - pip install hypothesis
  - pip install pytest-cov
  - pip install codecov
  - pip install tox
  
script: 
  - tox

after_success:
  - codecov