name: Build docker image

on:
  push:
    branches: [ master ]
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        # - uses: mr-smithers-excellent/docker-build-push@v3
        - uses: docker/build-push-action@v1
          with:
            repository: threefoldtech/js-ng
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            dockerfile: jumpscale/install/Dockerfile
            tags: latest